# Generated by Django 3.1.4 on 2021-02-03 13:28

import app.views
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categorie",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Citie",
            fields=[
                ("code", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Countrie",
            fields=[
                (
                    "code",
                    models.CharField(max_length=2, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Picture",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "picture1",
                    models.ImageField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to=app.models.Picture.generate_filename,
                    ),
                ),
                (
                    "picture2",
                    models.ImageField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to=app.models.Picture.generate_filename,
                    ),
                ),
                (
                    "picture3",
                    models.ImageField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to=app.models.Picture.generate_filename,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, null=True)),
                ("description", models.TextField(null=True)),
                ("price", models.FloatField(default=1.0, null=True)),
                (
                    "categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.categorie"
                    ),
                ),
                (
                    "pictures",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.picture"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=50, null=True)),
                ("password", models.CharField(max_length=50, null=True)),
                ("first_name", models.CharField(max_length=50, null=True)),
                ("last_name", models.CharField(max_length=50, null=True)),
                ("birth_date", models.DateField(null=True)),
                ("address", models.CharField(max_length=100, null=True)),
                ("phone_number", models.IntegerField(null=True)),
                (
                    "postal_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.citie"
                    ),
                ),
                (
                    "products",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.product"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                ("code", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, null=True)),
                (
                    "country",
                    models.ForeignKey(
                        default="1",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.countrie",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="citie",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.countrie"
            ),
        ),
        migrations.AddField(
            model_name="citie",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.region"
            ),
        ),
    ]
