# Generated by Django 3.1.4 on 2021-02-06 01:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_auto_20210205_2349"),
    ]

    operations = [
        migrations.AlterField(
            model_name="picture",
            name="picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=(
                    "C:\\Users\\Mathis\\PycharmProjects\\LeBonRecoin\\pictures",
                ),
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.date(2021, 2, 6), editable=False
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.date(2021, 2, 6), editable=False
            ),
        ),
    ]
