# Generated by Django 3.1.4 on 2021-02-06 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_auto_20210206_0235"),
    ]

    operations = [
        migrations.AlterField(
            model_name="picture",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="picture/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(default=10, null=True),
        ),
    ]
