# Generated by Django 3.1.4 on 2021-02-06 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_auto_20210206_0313"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favorite",
            name="product",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="app.product",
            ),
        ),
        migrations.AlterField(
            model_name="favorite",
            name="user",
            field=models.ForeignKey(
                default="", on_delete=django.db.models.deletion.CASCADE, to="app.user"
            ),
        ),
        migrations.AlterField(
            model_name="picture",
            name="product",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="app.product",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="state",
            field=models.ForeignKey(
                default="", on_delete=django.db.models.deletion.CASCADE, to="app.state"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="user",
            field=models.ForeignKey(
                default="", on_delete=django.db.models.deletion.CASCADE, to="app.user"
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="country",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="app.countrie",
            ),
        ),
    ]
