# Generated by Django 3.1.4 on 2021-02-06 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_auto_20210206_0320"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="app.address"
            ),
            preserve_default=False,
        ),
    ]
