# Generated by Django 3.1.4 on 2021-02-06 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_auto_20210206_0325"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="address",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
