# Generated by Django 3.1.4 on 2021-02-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0021_auto_20210206_1824"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="address",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="phone_number",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="picture",
            name="picture_1",
            field=models.ImageField(blank=True, null=True, upload_to="pictures/"),
        ),
        migrations.AlterField(
            model_name="picture",
            name="picture_2",
            field=models.ImageField(blank=True, null=True, upload_to="pictures/"),
        ),
        migrations.AlterField(
            model_name="picture",
            name="picture_3",
            field=models.ImageField(blank=True, null=True, upload_to="pictures/"),
        ),
    ]
