# Generated by Django 3.1.4 on 2021-02-07 20:37

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0022_auto_20210207_2047"),
    ]

    operations = [
        migrations.AlterField(
            model_name="picture",
            name="picture_1",
            field=models.ImageField(
                blank=True, null=True, upload_to=app.models.Picture.generate_filename
            ),
        ),
        migrations.AlterField(
            model_name="picture",
            name="picture_2",
            field=models.ImageField(
                blank=True, null=True, upload_to=app.models.Picture.generate_filename
            ),
        ),
        migrations.AlterField(
            model_name="picture",
            name="picture_3",
            field=models.ImageField(
                blank=True, null=True, upload_to=app.models.Picture.generate_filename
            ),
        ),
    ]
